### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by aku1310** [aku1310/se-club#5]
Improve documentation to explain about the website.

**Comment by ghost** [comment]
Hey Aku, Hope you're having a good day! I want to work on the readme file can you assign this to me ^-^

**Comment by aku1310** [comment]
Hi @Mridularora18 , thanks for your interest in contributing to this repo. But unfortunately, as of now, only the members of the club can contribute 😅

**Comment by harshraj78** [comment]
Assign me this too
